spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:/home/iza/Desktop/Notatki/Kursy/todo-app/todo-db'
  jpa:
    hibernate:
      ddl-auto: validate